import type { Metadata } from "next";
import "./globals.css";
import { Bodoni_Moda, Nunito_Sans } from "next/font/google";
import React from "react";

const bodoni = Bodoni_Moda({
    subsets: ["latin"],
    variable: "--font-heading",
});

const nunito = Nunito_Sans({
    subsets: ["latin"],
    variable: "--font-body",
});


export const metadata: Metadata = {
    title: "AltoraTrvl",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${bodoni.variable} ${nunito.variable} w-screen h-screen`}>
        {children}
        </body>
        </html>
    );
}