query getAllAgencies {
    agencies {
        id
        name
        slug
        logo
        theme
    }
}

query getAgencyBySlug($slug: String!){
    agency(slug: $slug){
        id
        name
        slug
        theme
        logo
        members {
            role
            user {
                id
                name
                image
            }
        }
    }
}

mutation addAgency($data: AgencyInput!){
    agency: addAgency(data: $data){
        id
        name
        slug
    }
}

mutation updateAgency($id: ID!, $data: AgencyInput!){
    agency: updateAgency(id: $id, data: $data){
        id
        name
        slug
        theme
    }
}

mutation addAgencyMember($data: AgencyMemberInput!){
    addAgencyMember(data: $data){
        agency {
            id
            name
        }
    }
}